version: '3'
services:
  dashboard:
    build: './dashboard'
    ports:
      - "3000:3000"

  api:
    build: './api'
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/guardrail

  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  nginx:
    image: "nginx:latest"
    ports:
      - "8080:8080"
    volumes:
      #- ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - dashboard
      - api
